services:
  api:
    build:
      context: .
      dockerfile: ./docker/local/php/Dockerfile
    container_name: api
    volumes:
      - .:/app
    ports:
      - '80:8080'
    depends_on:
      - db
      - db_test
  db:
    image: mysql:8.0.36
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/local/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
  db_test:
    image: mysql:8.0.36
    container_name: db_test
    environment:
      MYSQL_ROOT_PASSWORD: 'l11_user_password'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'l11_db_test'
      MYSQL_USER: 'l11_user_test'
      MYSQL_PASSWORD: 'l11_user_password'
      MYSQL_TCP_PORT: 3307
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - ./docker/local/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    tmpfs:
      - /var/lib/mysql
    ports:
      - 3307:3307
    expose:
      - 3307
volumes:
    db-data:
        driver: local